language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/httpbin

install:
    - pip install -U platformio

script:
    - platformio ci --project-conf=examples/httpbin/platformio.ini --lib="."
